#!/bin/sh

WIN_PATCHES=`rospack find win_patches`
ROSCONSOLE=`rospack find rosconsole`
ROSCPP=`rospack find roscpp`
ROSCPP=`rospack find rospy`

cp ${WIN_PATCHES}/updates/ros_comm/tools/rosconsole/rosbuild.cmake ${ROSCONSOLE}/
cp ${WIN_PATCHES}/updates/ros_comm/clients/cpp/roscpp/cmake/rosbuild2.cmake ${ROSCPP}/cmake
cp ${WIN_PATCHES}/updates/ros_comm/clients/rospy/cmake/rosbuild2.cmake ${ROSPY}/cmake
cp ${WIN_PATCHES}/updates/ros_comm/clients/rospy/scripts/genutil.py ${ROSPY}/scripts

if [ $? -eq 0 ]; then
  echo "Successfully patched."
else
  echo "Failed to patch, trying with sudo"
  sudo cp ${WIN_PATCHES}/updates/ros_comm/tools/rosconsole/rosbuild.cmake ${ROSCONSOLE}/
  sudo cp ${WIN_PATCHES}/updates/ros_comm/clients/cpp/roscpp/cmake/rosbuild2.cmake ${ROSCPP}/cmake
  sudo cp ${WIN_PATCHES}/updates/ros_comm/clients/rospy/cmake/rosbuild2.cmake ${ROSPY}/cmake
  sudo cp ${WIN_PATCHES}/updates/ros_comm/clients/rospy/scripts/genutil.py ${ROSPY}/scripts
  if [ $? -eq 0 ]; then
    echo "Successfully patched."
  else
    echo "Failed to patch"
  fi
fi
  
