#!/bin/sh

#!/bin/bash

# We are assuming that all source stacks are two directories below this and nowhere else.

DIR=`dirname $0`
PATCH_DIR=$DIR/patches
ROOT_DIR=$DIR/../..

echo "PATCHING"
echo ""
echo "  Dir..........$DIR"
echo "  Patch Dir....$PATCH_DIR"
echo "  Source Dir...$ROOT_DIR"
echo ""

cd $ROOT_DIR
for i in $PATCH_DIR/*.patch; do
  echo "# $i"
  patch -p0 < $i
done

 
