#!/bin/bash

# This requires us to have ros deps and easy_install here.

echo " - workspace: ${WORKSPACE}"
echo " - cleaning out old builds"
rm -rf ${WORKSPACE}/mingw
rm -rf ${WORKSPACE}/ros
sudo pip install -U vcstools rosinstall
sudo apt-get install mercurial xz-utils flex bison yasm autoconf libtool intltool scons
rosinstall --catkin ${WORKSPACE}/ros https://raw.github.com/stonier/win_ros/master/mingw_jenkins.rosinstall
export MINGW_INSTALL_PREFIX=${WORKSPACE}/mingw
cd ${WORKSPACE}/ros/win_ros/mingw/mingw_cross
make compile

