#!/bin/bash

# This requires us to have ros deps and easy_install here.

echo " - workspace: ${WORKSPACE}"
echo " - cleaning out old builds"
rm -rf ${WORKSPACE}/mingw
rm -rf ${WORKSPACE}/ros
sudo apt-get install -y ros-electric-ros-base
rosinstall ${WORKSPACE}/ros https://raw.github.com/stonier/win_ros/master/mingw_electric_overlay.rosinstall
cd ${WORKSPACE}/ros; . ./setup.bash
export MINGW_INSTALL_PREFIX=${WORKSPACE}/mingw
roscd mingw_cross; make compile
#rm -rf /opt/win

